import { BoardData } from '../../../services/types/frontendtypes/frontend';

// ========== 假数据（仅用于无缓存时展示，不写入 localStorage；后期接真实数据可整块删除）==========
const MOCK_CARDS = [
  {
    id: 'card-1',
    jobTitle: 'Frontend Engineer',
    companyName: 'Company A',
    statusId: 'col-todo',
    jobLink: 'https://example.com/job/1',
    sourcePlatform: 'LinkedIn',
    expired: false,
    jobLocation: 'Auckland CBD',
    description: 'Frontend architecture and React stack development.',
    appliedTime: undefined,
    tags: ['React', 'TypeScript'],
    comments: 'HR responds quickly',
    extra: { contactInfo: 'hr@companya.com', file: [] },
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-01-25'),
  },
  {
    id: 'card-2',
    jobTitle: 'Full Stack Developer',
    companyName: 'Startup B',
    statusId: 'col-todo',
    jobLink: 'https://example.com/job/2',
    sourcePlatform: 'Seek',
    expired: false,
    jobLocation: 'Wellington',
    description: 'Full stack development, Node + React.',
    appliedTime: undefined,
    tags: ['Node.js', 'React'],
    comments: '',
    extra: { contactInfo: undefined, file: ['resume.pdf'] },
    createdAt: new Date('2025-01-26'),
    updatedAt: new Date('2025-01-26'),
  },
  {
    id: 'card-3',
    jobTitle: 'React Developer',
    companyName: 'Tech Corp C',
    statusId: 'col-applied',
    jobLink: 'https://example.com/job/3',
    sourcePlatform: 'Company website',
    expired: false,
    jobLocation: 'Christchurch',
    description: 'Mid to senior React developer, large-scale project experience preferred.',
    appliedTime: new Date('2025-01-20'),
    tags: ['React', 'Vite'],
    comments: 'Applied, waiting for feedback',
    extra: { contactInfo: undefined, file: [] },
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: 'card-4',
    jobTitle: 'Software Engineer',
    companyName: 'Tech Co D',
    statusId: 'col-applied',
    jobLink: 'https://example.com/job/4',
    sourcePlatform: 'Company website',
    expired: false,
    jobLocation: 'Hamilton',
    description: 'Software engineer, core product R&D.',
    appliedTime: new Date('2025-01-22'),
    tags: ['Java', 'Go'],
    comments: '',
    extra: { contactInfo: 'recruit@techd.com', file: [] },
    createdAt: new Date('2025-01-21'),
    updatedAt: new Date('2025-01-22'),
  },
  {
    id: 'card-5',
    jobTitle: 'Senior Frontend',
    companyName: 'Company E',
    statusId: 'col-interview',
    jobLink: 'https://example.com/job/5',
    sourcePlatform: 'Seek',
    expired: false,
    jobLocation: 'Tauranga',
    description: 'Senior frontend, team lead experience.',
    appliedTime: new Date('2025-01-15'),
    tags: ['React', 'Team lead'],
    comments: 'First round done, second round scheduled. Need to prepare for the interview.',
    extra: { contactInfo: undefined, file: [] },
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-01-18'),
  },
  {
    id: 'card-6',
    jobTitle: 'Frontend Architect',
    companyName: 'Global Co F',
    statusId: 'col-offered',
    jobLink: 'https://example.com/job/6',
    sourcePlatform: 'LinkedIn',
    expired: false,
    jobLocation: 'Dunedin',
    description: 'Frontend architecture, tech selection and standards.',
    appliedTime: new Date('2025-01-10'),
    tags: ['Architecture', 'React', 'Performance'],
    comments: 'Offer received, considering',
    extra: { contactInfo: 'hr@companyf.com', file: ['offer.pdf'] },
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-28'),
  },
  {
    id: 'card-7',
    jobTitle: 'Web Developer',
    companyName: 'Agency G',
    statusId: 'col-rejected',
    jobLink: 'https://example.com/job/7',
    sourcePlatform: 'Seek',
    expired: true,
    jobLocation: 'Napier',
    description: 'Web development, multi-project collaboration.',
    appliedTime: new Date('2025-01-05'),
    tags: ['Vue', 'CSS'],
    comments: 'Role closed',
    extra: { contactInfo: undefined, file: [] },
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-12'),
  },
];

/** 假卡 id 集合，保存时过滤掉这些 id，避免假数据被写入缓存 */
export const MOCK_CARD_IDS = new Set(MOCK_CARDS.map((c) => c.id));

/** 无缓存或缓存里无卡片时，返回用于展示的 board（列 + 假卡片）。不写入存储。 */
export function getBoardWithMockCards(board: BoardData): BoardData {
  if (board.cards?.length) return board;
  return { ...board, cards: [...MOCK_CARDS] };
}
// ========== 假数据 end ==========

export const INITIAL_DATA: BoardData = {
  columns: [
    { id: 'col-todo', name: 'Wish list', order: 1, isDefault: true, customAttributes: {} },
    { id: 'col-applied', name: 'Applied', order: 2, isDefault: true, customAttributes: {} },
    { id: 'col-interview', name: 'Interviewing', order: 3, isDefault: true, customAttributes: {} },
    { id: 'col-offered', name: 'Offered', order: 4, isDefault: true, customAttributes: {} },
    { id: 'col-rejected', name: 'Rejected', order: 5, isDefault: true, customAttributes: {} },
  ],
  cards: [], // 正式数据为空；展示时由 getBoardWithMockCards 注入假数据
};